export default {
  EMAIL_ALREADY_EXISTS: 'emalex',
  TOKEN_ERROR: 'tokeR',
  USER_NOT_FOUND: 'usrnf',
  WRONG_PASSWORD: 'wrnpwd',
  MISSING_PROP: 'mp',
  TOKEN_NOT_FOUND: 'tknf',
  BOOK_NOT_FOUND: 'bknf',
  CLASS_NOT_FOUND_OR_NOT_AUTHORIZED: 'clsnfonthrzd',
  USERS_BOOKS_NOT_FOUND: 'usrsbksnf',
  USERS_MOVIES_NOT_FOUND: 'usrsmvssnf',
  USERS_MUSICS_NOT_FOUND: 'usrsmscssnf',
  UR_LINK_COULDNT_CREATED: 'urlnkcldntcrtd',
  ALREADY_EXISTS: 'alrdyxsts',
  NOT_FOUND: 'enfnd',
  UUID_NOT_VALID: 'idnvornf',
  RESOURCE_NOT_APPROVED: 'rsrcnprvd',
};
